### ISSUE TITLE
ワークフローが古い

### ISSUE THREAD

**Issue by Seasawher** [lean-ja/tactic-cheatsheet#54]
この部分が古い．`lake-packages` はもう使わない．

```yml
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ./lake-packages
          key: deps-${{ runner.os }}-${{ hashFiles('lean-toolchain') }}-${{ hashFiles('lake-manifest.json') }}
          restore-keys: |
            deps-${{ runner.os }}-${{ hashFiles('lean-toolchain') }}
```
